services:

  database:
    container_name: database
    image: postgres:16.1-alpine
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${PS_USER}
      POSTGRES_PASSWORD: ${PS_PASSWORD}
