// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID            int        `json:"id"`
	PostID        int        `json:"postId"`
	AuthorID      *int       `json:"authorId,omitempty"`
	Content       string     `json:"content"`
	CreatedAt     string     `json:"createdAt"`
	ReplyComments []*Comment `json:"replyComments"`
}

type Mutation struct {
}

type NewComment struct {
	PostID          int    `json:"postId"`
	AuthorID        *int   `json:"authorId,omitempty"`
	Content         string `json:"content"`
	ParentCommentID *int   `json:"parentCommentId,omitempty"`
}

type NewPost struct {
	Title          string `json:"title"`
	AuthorID       *int   `json:"authorId,omitempty"`
	Content        string `json:"content"`
	CanBeCommented bool   `json:"canBeCommented"`
}

type Post struct {
	ID             int        `json:"id"`
	Title          string     `json:"title"`
	AuthorID       *int       `json:"authorId,omitempty"`
	Content        string     `json:"content"`
	CreatedAt      string     `json:"createdAt"`
	CanBeCommented bool       `json:"canBeCommented"`
	Comments       []*Comment `json:"comments,omitempty"`
}

type Query struct {
}

type UpdatePost struct {
	ID             int     `json:"id"`
	Title          *string `json:"title,omitempty"`
	Content        *string `json:"content,omitempty"`
	CanBeCommented *bool   `json:"canBeCommented,omitempty"`
}
